name: Save licenses report

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_dispatch:

concurrency:
  group: licenses-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: licensed cache 

